import 'dart:async';
import '../../../core/constants/app_constants.dart';
import '../../../models/level_data.dart';
import '../../../services/storage_service.dart';
import '../../generator/grid_level_generator.dart';
import '../../solver/puzzle_solver.dart';
import '../cache/puzzle_cache.dart';

class PuzzleRepository {
  final StorageService storageService;
  late final PuzzleCache _cache;
  bool _isInitialized = false;

  PuzzleRepository({required this.storageService}) {
    _cache = PuzzleCache(storageService);
  }

  bool get isInitialized => _isInitialized;

  /// Initializes the repository on app start.
  /// Generates initial pack (Levels 1–50) if missing, then launches background staged generation.
  Future<void> init() async {
    if (_isInitialized) return;

    // First launch check: ensure initial batch (1-50) exists
    if (!_cache.hasLevel(1)) {
      _generateInitialPack(1, 50);
    }

    _isInitialized = true;

    // Launch background staged generation for upcoming level tiers asynchronously
    unawaited(_launchBackgroundGeneration());
  }

  /// Synchronously/fast prepares initial pack (Levels 1-50) for immediate play.
  void _generateInitialPack(int startLevel, int endLevel) {
    for (int i = startLevel; i <= endLevel; i++) {
      final cached = _cache.getLevel(i);
      if (cached == null || !_isV2Level(cached)) {
        final level = GridLevelGenerator.generateGridLevel(i);
        _cache.saveLevel(level);
      }
    }
  }

  /// Asynchronously generates higher level tiers in non-blocking background stages.
  Future<void> _launchBackgroundGeneration() async {
    final stages = [
      const [51, 100],
      const [101, 250],
      const [251, 500],
      const [501, 1000],
    ];

    for (final stage in stages) {
      final start = stage[0];
      final end = stage[1];
      for (int i = start; i <= end; i++) {
        final cached = _cache.getLevel(i);
        if (cached == null || !_isV2Level(cached)) {
          final level = GridLevelGenerator.generateGridLevel(i);
          await _cache.saveLevel(level);
          // Yield execution frame to keep UI thread responsive
          await Future.delayed(Duration.zero);
        }
      }
    }
  }

  /// Retrieves a validated level by number. Uses local cache if available and valid (v2 engine), or generates deterministically on demand.
  LevelData getLevel(int levelNumber) {
    final clampedNumber = levelNumber.clamp(1, AppConstants.totalLevels);

    // 1. Try local persistent cache
    final cached = _cache.getLevel(clampedNumber);
    if (cached != null && _isV2Level(cached)) {
      return cached;
    }

    // 2. Generate deterministically on demand using Reverse Inter-blocking Engine
    final generated = GridLevelGenerator.generateGridLevel(clampedNumber);
    _cache.saveLevel(generated);
    return generated;
  }

  /// Checks if a cached level was generated by the v2 Reverse Puzzle Engine.
  bool _isV2Level(LevelData level) {
    final title = level.title;
    return title.contains('NEON') ||
        title.contains('CYBER') ||
        title.contains('EMERALD') ||
        title.contains('TITAN');
  }
}

